server:
  port: 8020
  servlet:
    context-path: /qq
#    session:
#      cookie:
#        name: UISESSION
security:
  oauth2:
    client:
      client-id: qq
      client-secret: 111
      access-token-uri: http://auth-server:8000/auth/oauth/token
      user-authorization-uri: http://auth-server:8000/auth/oauth/authorize
      pre-established-redirect-uri: http://client-wx:8010/qq/callback
      client-authentication-scheme: header
      authentication-scheme: header
      grant-type: authorization_code
    resource:
      token-info-uri: http://auth-server:8000/auth/oauth/check_token
    sso:
      login-path: /callback
