server:
  port: 8050
  servlet:
    context-path: /api
security:
  oauth2:
#    client:
#      client-id: api
#      client-secret: 111
#      access-token-uri: http://auth-server:8000/auth/oauth/token
#      user-authorization-uri: http://auth-server:8000/auth/oauth/authorize
#      pre-established-redirect-uri: http://client-api:8050/api/auth/code
#      client-authentication-scheme: header
#      authentication-scheme: header
#      grant-type: authorization_code
    resource:
      token-info-uri: http://auth-server:8000/auth/oauth/check_token
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          api:
#            client-id: api
#            client-secret: 111
#            redirect-uri: http://client-api:8050/api/auth/code
#            authorization-grant-type: authorization_code
#        provider:
#          api:
#            authorization-uri: http://auth-server:8000/auth/oauth/authorize
#            token-uri: http://auth-server:8000/auth/oauth/token


